// <auto-generated />
using System;
using EasyTab.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyTab.Services.Migrations
{
    [DbContext(typeof(_220030Context))]
    [Migration("20260503123619_LocaleImageUpdate")]
    partial class LocaleImageUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyTab.Services.Database.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07D81A11B5");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EasyTab.Services.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Cities__3214EC070B29E5C4");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Countrie__3214EC071B510B79");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Favourit__3214EC0732D7945E");

                    b.HasIndex("LocaleId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Locale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<TimeOnly>("EndOfWorkingHours")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("LengthOfReservation")
                        .HasColumnType("float");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("StartOfWorkingHours")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__Locales__3214EC07B3B220E9");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Locales");
                });

            modelBuilder.Entity("EasyTab.Services.Database.LocaleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LocaleIm__3214EC0720D3ED62");

                    b.HasIndex("LocaleId");

                    b.ToTable("LocaleImages");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reaction__3214EC073F1AB34B");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("EasyTab.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reservat__3214EC07938B47B8");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reviews__3214EC07EE2BA60A");

                    b.HasIndex("LocaleId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07D3F60231");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<double>("Xcoordinate")
                        .HasColumnType("float")
                        .HasColumnName("XCoordinate");

                    b.Property<double>("Ycoordinate")
                        .HasColumnType("float")
                        .HasColumnName("YCoordinate");

                    b.HasKey("Id")
                        .HasName("PK__Tables__3214EC07285A725C");

                    b.HasIndex("LocaleId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("EasyTab.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07B093556C");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EasyTab.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3214EC074D5F43C8");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Workers__3214EC07C018FE00");

                    b.HasIndex("LocaleId");

                    b.HasIndex("UserId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<double>("Xcoordinate")
                        .HasColumnType("float")
                        .HasColumnName("XCoordinate");

                    b.Property<double>("Ycoordinate")
                        .HasColumnType("float")
                        .HasColumnName("YCoordinate");

                    b.HasKey("Id")
                        .HasName("PK__Zones__3214EC07EDBBD183");

                    b.HasIndex("LocaleId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("EasyTab.Services.Database.City", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__CountryI__3B75D760");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Favourite", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Locale", "Locale")
                        .WithMany("Favourites")
                        .HasForeignKey("LocaleId")
                        .IsRequired()
                        .HasConstraintName("FK__Favourite__Local__74AE54BC");

                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Favourite__UserI__75A278F5");

                    b.Navigation("Locale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Locale", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Category", "Category")
                        .WithMany("Locales")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Locales__Categor__5535A963");

                    b.HasOne("EasyTab.Services.Database.City", "City")
                        .WithMany("Locales")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Locales__CityId__5441852A");

                    b.HasOne("EasyTab.Services.Database.User", "Owner")
                        .WithMany("Locales")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Locales__OwnerId__5629CD9C");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EasyTab.Services.Database.LocaleImage", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Locale", "Locale")
                        .WithMany("LocaleImages")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LocaleIma__Local__787EE5A0");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Reaction", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Review", "Review")
                        .WithMany("Reactions")
                        .HasForeignKey("ReviewId")
                        .IsRequired()
                        .HasConstraintName("FK__Reactions__Revie__6E01572D");

                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reactions__UserI__6EF57B66");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Reservation", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__Table__656C112C");

                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__UserI__6477ECF3");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Review", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Locale", "Locale")
                        .WithMany("Reviews")
                        .HasForeignKey("LocaleId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__LocaleI__6B24EA82");

                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__6A30C649");

                    b.Navigation("Locale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Table", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Locale", "Locale")
                        .WithMany("Tables")
                        .HasForeignKey("LocaleId")
                        .IsRequired()
                        .HasConstraintName("FK__Tables__LocaleId__5CD6CB2B");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("EasyTab.Services.Database.UserRole", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__45F365D3");

                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__44FF419A");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Worker", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Locale", "Locale")
                        .WithMany("Workers")
                        .HasForeignKey("LocaleId")
                        .IsRequired()
                        .HasConstraintName("FK__Workers__LocaleI__59FA5E80");

                    b.HasOne("EasyTab.Services.Database.User", "User")
                        .WithMany("Workers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Workers__UserId__59063A47");

                    b.Navigation("Locale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Zone", b =>
                {
                    b.HasOne("EasyTab.Services.Database.Locale", "Locale")
                        .WithMany("Zones")
                        .HasForeignKey("LocaleId")
                        .IsRequired()
                        .HasConstraintName("FK__Zones__LocaleId__5FB337D6");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Category", b =>
                {
                    b.Navigation("Locales");
                });

            modelBuilder.Entity("EasyTab.Services.Database.City", b =>
                {
                    b.Navigation("Locales");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Locale", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("LocaleImages");

                    b.Navigation("Reviews");

                    b.Navigation("Tables");

                    b.Navigation("Workers");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Review", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EasyTab.Services.Database.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EasyTab.Services.Database.User", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("Locales");

                    b.Navigation("Reactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");

                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
